// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Linq;
using Microsoft.EntityFrameworkCore;
using DotNetCloud.Core.Models; // For User, Role, Team, UserRole, UserTeam
using DotNetCloud.Data.Models; // For Setting
using DotNetCloud.Core;

namespace DotNetCloud.Data
{
    public partial class DotNetCloudDbContext : DbContext
    {
        public DotNetCloudDbContext() { }
        public DotNetCloudDbContext(DbContextOptions<DotNetCloudDbContext> options) : base(options) { }

        public virtual DbSet<Setting> Settings { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<Role> Roles { get; set; }
        public virtual DbSet<Team> Teams { get; set; }
        public virtual DbSet<UserRole> UserRoles { get; set; }
        public virtual DbSet<UserTeam> UserTeams { get; set; }

        

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<Setting>().HasNoKey();
            modelBuilder.Entity<User>(entity =>
            {
                entity.HasKey(e => e.Id);
                entity.Property(e => e.UserName).IsRequired().HasMaxLength(100);
                entity.Property(e => e.Email).IsRequired().HasMaxLength(255);
                entity.Property(e => e.PasswordHash).IsRequired();
                entity.Property(e => e.PasswordSalt).IsRequired();
            });
            modelBuilder.Entity<Role>(entity =>
            {
                entity.HasKey(e => e.Id);
                entity.Property(e => e.Name).IsRequired().HasMaxLength(50);
            });
            modelBuilder.Entity<Team>(entity =>
            {
                entity.HasKey(e => e.Id);
                entity.Property(e => e.Name).IsRequired().HasMaxLength(100);
            });
            modelBuilder.Entity<UserRole>(entity =>
            {
                entity.HasKey(e => new { e.UserId, e.RoleId });
                entity.HasOne(e => e.User).WithMany(u => u.UserRoles).HasForeignKey(e => e.UserId);
                entity.HasOne(e => e.Role).WithMany(r => r.UserRoles).HasForeignKey(e => e.RoleId);
            });
            modelBuilder.Entity<UserTeam>(entity =>
            {
                entity.HasKey(e => new { e.UserId, e.TeamId });
                entity.HasOne(e => e.User).WithMany(u => u.UserTeams).HasForeignKey(e => e.UserId);
                entity.HasOne(e => e.Team).WithMany(t => t.UserTeams).HasForeignKey(e => e.TeamId);
            });

            // Seed roles from RoleType enum
            var roleEnumValues = Enum.GetValues(typeof(RoleType)).Cast<RoleType>();
            var roleEntities = roleEnumValues.Select(e => new Role
            {
                Id = GuidFromRole(e),
                Name = e.ToString()
            });
            modelBuilder.Entity<Role>().HasData(roleEntities);
        }

        // Helper to generate deterministic GUID for each role
        private static Guid GuidFromRole(RoleType role)
        {
            return GuidUtility.Create(GuidUtility.UrlNamespace, $"Role:{role}");
        }
    }
}

public static class GuidUtility
{
    public static readonly Guid UrlNamespace = new Guid("6ba7b811-9dad-11d1-80b4-00c04fd430c8");
    public static Guid Create(Guid namespaceId, string name)
    {
        var namespaceBytes = namespaceId.ToByteArray();
        var nameBytes = System.Text.Encoding.UTF8.GetBytes(name);
        var data = namespaceBytes.Concat(nameBytes).ToArray();
        using var sha1 = System.Security.Cryptography.SHA1.Create();
        var hash = sha1.ComputeHash(data);
        var newGuid = new byte[16];
        Array.Copy(hash, 0, newGuid, 0, 16);
        newGuid[6] = (byte)((newGuid[6] & 0x0F) | 0x50);
        newGuid[8] = (byte)((newGuid[8] & 0x3F) | 0x80);
        return new Guid(newGuid);
    }
}