// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DotNetCloud.Data.Models;

public partial class Setting
{
    public string Key { get; set; }

    public string Value { get; set; }
}